[package]
name = "atomic_swap"
version = "0.0.0"

[dependencies.AptosFramework]
git = 'https://github.com/aptos-labs/aptos-core'
subdir = 'aptos-move/framework/aptos-framework'
rev = '908aff867fcc1e1b12f058d474329097ab96f14b'

[addresses]
atomic_swap = "0x2"
comp_user = "0x3"
