[package]
name = "atomic_swap"
version = "0.0.0"

[dependencies]
AptosFramework = { local = "../../aptos-core/aptos-move/framework/aptos-framework" }

[addresses]
atomic_swap = "0x1"
init_user = "0x1"
comp_user = "0x2"
